
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "email_function", targetNamespace = "http://email_webservice")
@XmlSeeAlso({
    ObjectFactory.class
})

public interface EmailFunction {
    /**
     * 
     * @param url
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "validateEmailAddressReturn", targetNamespace = "http://email_webservice")
    @RequestWrapper(localName = "validateEmailAddress", targetNamespace = "http://email_webservice", className = "client.ValidateEmailAddress")
    @ResponseWrapper(localName = "validateEmailAddressResponse", targetNamespace = "http://email_webservice", className = "client.ValidateEmailAddressResponse")
    public String validateEmailAddress(
        @WebParam(name = "_url", targetNamespace = "http://email_webservice")
        String url);
    /**
     * 
     * @param payload
     * @param url
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmailBatch", targetNamespace = "http://email_webservice", className = "client.SendEmailBatch")
    @ResponseWrapper(localName = "sendEmailBatchResponse", targetNamespace = "http://email_webservice", className = "client.SendEmailBatchResponse")
    public void sendEmailBatch(
        @WebParam(name = "url", targetNamespace = "http://email_webservice")
        String url,
        @WebParam(name = "_payload", targetNamespace = "http://email_webservice")
        String payload);
    /**
     * 
     * @param payload
     * @param url
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmail", targetNamespace = "http://email_webservice", className = "client.SendEmail")
    @ResponseWrapper(localName = "sendEmailResponse", targetNamespace = "http://email_webservice", className = "client.SendEmailResponse")
    public void sendEmail(
        @WebParam(name = "_url", targetNamespace = "http://email_webservice")
        String url,
        @WebParam(name = "_payload", targetNamespace = "http://email_webservice")
        String payload);

}
